ARG BASE=docker.io/debian:sid

FROM ghcr.io/initramfs-modules/initramfs:latest as initrd

FROM $BASE as builder

COPY --from=initrd /efi /efi

ENV REPO=/_tmp

RUN --mount=target=$REPO $REPO/container/kernel-tiny.sh

FROM scratch
COPY --from=builder /boot /boot
COPY --from=builder /lib/modules /lib/modules
COPY --from=initrd /efi /efi
