ARG BASE=docker.io/debian:sid

FROM $BASE

#as builder

#FROM initramfs-modules/initramfs:latest as initrd
# grab /efi/kernel/initrd.img
#COPY --from=initrd /efi /efi

ENV REPO=/_tmp

RUN apt-get update -y -qq && apt-get upgrade -y -qq && DEBIAN_FRONTEND=noninteractive apt-get install -y -qq --no-install-recommends -o Dpkg::Use-Pty=0 \
    dracut-core \
    bc kmod git squashfs-tools cpio dracut-core ca-certificates apt-utils ca-certificates git fakeroot gzip \
    wget linux-base sudo libelf1 python3 dkms build-essential rsync linux-headers-generic \
    autoconf build-essential libssl-dev gawk openssl libssl-dev libelf-dev libudev-dev libpci-dev flex bison cpio zstd wget bc kmod file \
    && apt-get clean && rm -rf /usr/lib/modules/*

# grab /efi/kernel/initrd.img
# COPY --from=initrd /efi /efi

RUN --mount=target=$REPO $REPO/container/testme.sh

#FROM scratch
#COPY --from=builder /efi /efi
