FROM ghcr.io/initramfs-modules/kernel-tiny as kernel

FROM ghcr.io/initramfs-modules/boot as boot

FROM docker.io/alpine

ENV REPO=/_tmp

RUN --mount=target=$REPO $REPO/container/packages.sh

COPY --from=kernel /boot /boot
COPY --from=kernel /lib/modules /lib/modules
COPY --from=kernel /efi /efi
COPY --from=boot /efi /efi

RUN find /lib/modules/ /boot/ /efi/
