FROM ghcr.io/initramfs-modules/initramfs as initrd

FROM ghcr.io/initramfs-modules/kernel-tiny as kernel

ARG BASE=ghcr.io/initramfs-modules/alpine

FROM ghcr.io/initramfs-modules/alpine

ENV REPO=/_tmp

COPY --from=initrd /efi /
COPY --from=kernel /boot /
