FROM ghcr.io/initramfs-modules/initramfs as initrd

FROM ghcr.io/initramfs-modules/kernel-tiny as kernel

ARG BASE=docker.io/alpine

FROM $BASE

ENV REPO=/_tmp

RUN --mount=target=$REPO $REPO/container/packages.sh

ENV REPO=/_tmp

COPY --from=initrd /efi /efi
COPY --from=kernel /boot /boot