.PHONY: all setup clean run

# TODO use "type -P" to find basedir instead of hardcoding

all:
	@V=$(V) testdir="$(realpath ../)" ./test.sh --all
setup:
	@$(MAKE) --no-print-directory -C ../.. all
	@testdir="$(realpath ../)" ./test.sh --setup
clean:
	@testdir="$(realpath ../)" ./test.sh --clean
run:
	@testdir="$(realpath ../)" ./test.sh --run
