.PHONY: all setup clean run

all:
	@V=$(V) basedir="/usr/lib/dracut/" testdir="$(realpath ../)" ./test.sh --all

setup:
	@basedir="$(realpath ../..)" testdir="$(realpath ../)" ./test.sh --setup

clean:
	@basedir="$(realpath ../..)" testdir="$(realpath ../)" ./test.sh --clean

run:
	@basedir="$(realpath ../..)" testdir="$(realpath ../)" ./test.sh --run
