FROM docker.io/gentoo/portage as portage

# kernel and its dependencies in a separate builder
FROM docker.io/gentoo/stage3 as kernel
COPY --from=portage /var/db/repos/gentoo /var/db/repos/gentoo
RUN emerge -qv sys-kernel/gentoo-kernel-bin

FROM docker.io/gentoo/stage3
COPY --from=portage /var/db/repos/gentoo /var/db/repos/gentoo
COPY --from=kernel /boot /boot
COPY --from=kernel /lib/modules /lib/modules

# Only install `dmsetup`: attempting to install all of lvm2 fails due to missing kernel headers.
RUN echo 'sys-fs/lvm2 device-mapper-only -thin' > /etc/portage/package.use/lvm2

# workaround for https://bugs.gentoo.org/734022 whereby Gentoo does not support NFS4 with musl
# RUN echo 'net-fs/nfs-utils -nfsv4' > /etc/portage/package.use/nfs-utils

RUN echo 'app-emulation/qemu QEMU_SOFTMMU_TARGETS: x86_64 QEMU_USER_TARGETS: x86_64' > /etc/portage/package.use/qemu

RUN emerge -qv sys-kernel/dracut app-emulation/qemu

RUN emerge -qv \
    app-arch/cpio \
    app-shells/dash \
    net-fs/nfs-utils \
    net-misc/dhcp \
    sys-apps/busybox \
    sys-block/nbd \
    sys-block/parted \
    sys-block/thin-provisioning-tools \
    sys-fs/btrfs-progs \
    sys-fs/cryptsetup \
    sys-fs/dmraid \
    sys-fs/lvm2 \
    sys-fs/mdadm \
    sys-fs/multipath-tools \
    sys-fs/ntfs3g \
    sys-fs/squashfs-tools \
    && rm -rf /var/cache/* /usr/share/doc/* /usr/share/man/*
