FROM registry.opensuse.org/opensuse/tumbleweed-dnf:latest

RUN dnf -y install --setopt=install_weak_deps=False dracut qemu-kvm

RUN dnf -y install --setopt=install_weak_deps=False \
    dash asciidoc mdadm lvm2 dmraid cryptsetup nfs-utils nbd dhcp-server \
    strace libkmod-devel gcc bzip2 xz tar wget rpm-build make git bash-completion \
    sudo kernel dhcp-client qemu-kvm e2fsprogs \
    tcpdump iproute iputils kbd btrfsprogs tgt dbus-broker \
    iscsiuio open-iscsi which procps pigz parted squashfs ntfsprogs \
    && dnf -y update && dnf clean all
