FROM registry.opensuse.org/opensuse/tumbleweed-dnf:latest

# dracut
RUN dnf -y install --setopt=install_weak_deps=False dracut

# kernel
RUN dnf -y install --setopt=install_weak_deps=False kernel

# qemu
RUN dnf -y install --setopt=install_weak_deps=False qemu-kvm

# common
RUN dnf -y install --setopt=install_weak_deps=False btrfs-progs cryptsetup dash dmraid mdadm sed lvm2 make sudo e2fsprogs

RUN dnf -y install --setopt=install_weak_deps=False squashfs

RUN dnf -y install --setopt=install_weak_deps=False \
    nfs-utils nbd dhcp-server \
    libkmod-devel bzip2 xz tar wget bash-completion \
    dhcp-client qemu-kvm e2fsprogs \
    tcpdump iproute iputils kbd btrfsprogs tgt dbus-broker \
    iscsiuio open-iscsi which procps pigz parted ntfsprogs \
    && dnf -y update && dnf clean all
