FROM docker.io/archlinux

RUN pacman --noconfirm -Syu dracut qemu

RUN pacman --noconfirm -Syu \
    linux dash strace dhclient asciidoc cpio pigz squashfs-tools \
    btrfs-progs mdadm dmraid nfs-utils nfsidmap lvm2 nbd \
    dhcp multipath-tools vi tcpdump open-iscsi connman \
    git astyle which base-devel glibc parted ntfs-3g && yes | pacman -Scc

RUN useradd -m build
RUN su build -c 'cd && git clone https://aur.archlinux.org/perl-config-general.git && cd perl-config-general && makepkg -s --noconfirm'
RUN pacman -U --noconfirm ~build/perl-config-general/*.pkg.tar.*
RUN su build -c 'cd && git clone https://aur.archlinux.org/tgt.git && cd tgt && makepkg -s --noconfirm'
RUN pacman -U --noconfirm ~build/tgt/*.pkg.tar.*
RUN rm -fr ~build

