FROM docker.io/debian:sid

# Install needed packages for the dracut CI container
RUN apt-get update -y -qq && apt-get upgrade -y -qq && DEBIAN_FRONTEND=noninteractive apt-get install -y -qq --no-install-recommends -o Dpkg::Use-Pty=0 \
    asciidoc \
    astyle \
    btrfs-progs \
    busybox-static \
    bzip2 \
    ca-certificates \
    console-setup \
    cpio \
    cryptsetup \
    curl \
    dash \
    debhelper \
    debhelper-compat \
    docbook \
    docbook-xml \
    docbook-xsl \
    fdisk \
    g++ \
    git \
    iputils-arping \
    iputils-ping \
    isc-dhcp-client \
    isc-dhcp-server \
    kmod \
    less \
    libkmod-dev \
    linux-image-generic \
    lvm2 \
    make \
    mdadm \
    multipath-tools \
    nbd-client \
    network-manager \
    nfs-kernel-server \
    open-iscsi \
    parted \
    pigz \
    pkg-config \
    procps \
    qemu-system-x86 \
    quilt \
    shellcheck \
    squashfs-tools \
    strace \
    sudo \
    tcpdump \
    vim \
    wget \
    dracut-core \
    && apt-get clean

RUN cp /usr/bin/dracut /usr/lib/dracut/dracut.sh
