FROM docker.io/archlinux

# kernel
RUN pacman --noconfirm -Syu linux

# dracut
RUN pacman --noconfirm -Syu dracut

# common
RUN pacman --noconfirm -Syu \
    btrfs-progs cryptsetup dash dmraid mdadm sed lvm2 make sudo e2fsprogs bzip2 parted pigz procps kbd xz

# common - but distro specific name
RUN pacman --noconfirm -Syu gnupg squashfs-tools multipath-tools openssh qemu ntfs-3g busybox

# networking
RUN pacman --noconfirm -Syu \
    dhclient nfs-utils nfsidmap nbd dhcp open-iscsi

RUN pacman --noconfirm -Syu \
    base-devel glibc && yes | pacman -Scc

# tgt
RUN pacman --noconfirm -Syu perl-config-general libxslt docbook-xsl git && yes | pacman -Scc
RUN useradd -m build
RUN su build -c 'cd && git clone https://aur.archlinux.org/tgt.git && cd tgt && makepkg -s --noconfirm'
RUN pacman -U --noconfirm ~build/tgt/*.pkg.tar.*
RUN rm -fr ~build
