FROM registry.fedoraproject.org/fedora:latest

RUN dnf -y install --setopt=install_weak_deps=False dracut qemu-system-x86-core

RUN dnf -y install --setopt=install_weak_deps=False btrfs-progs cryptsetup dash dmraid mdadm sed lvm2

RUN dnf -y install --setopt=install_weak_deps=False squashfs-tools

RUN dnf -y install --setopt=install_weak_deps=False \
    pigz \
    nfs-utils \
    nbd \
    dhcp-server \
    scsi-target-utils \
    iscsi-initiator-utils \
    kmod-devel \
    gcc \
    bzip2 \
    xz \
    tar \
    wget \
    make \
    bash-completion \
    sudo \
    kernel \
    dhcp-client \
    e2fsprogs \
    tcpdump \
    iproute \
    iputils \
    dbus-daemon \
    kbd \
    which \
    parted \
    ntfsprogs \
    procps-ng \
    && dnf clean all

