FROM docker.io/debian:sid

RUN apt-get update -y -qq && apt-get upgrade -y -qq

# dracut, qemu
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y -qq --no-install-recommends -o Dpkg::Use-Pty=0 dracut-live dracut-network qemu-system-x86

# common
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y -qq --no-install-recommends -o Dpkg::Use-Pty=0 \
    btrfs-progs cryptsetup dash dmraid mdadm sed lvm2

# distro specific
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y -qq --no-install-recommends -o Dpkg::Use-Pty=0 \
    openssh-client multipath-tools squashfs-tools

RUN DEBIAN_FRONTEND=noninteractive apt-get install -y -qq --no-install-recommends -o Dpkg::Use-Pty=0 \
    binutils \
    busybox-static \
    bzip2 \
    ca-certificates \
    console-setup \
    curl \
    fdisk \
    iputils-arping \
    iputils-ping \
    isc-dhcp-client \
    isc-dhcp-server \
    kmod \
    libdmraid-dev \
    less \
    libkmod-dev \
    linux-image-generic \
    make \
    nbd-client \
    nbd-server \
    nfs-kernel-server \
    ntfs-3g \
    open-iscsi \
    parted \
    pigz \
    pkg-config \
    procps \
    sudo \
    tcpdump \
    tgt \
    thin-provisioning-tools \
    vim \
    wget \
    sysvinit-core \
    zstd \
    && apt-get clean

RUN cp /usr/bin/dracut /usr/lib/dracut/dracut.sh
