name: Container
on:
    push:
        branches: [ main ]
        paths:
            - 'test/container/**'
            - '.github/workflows/container.yml'
    pull_request:
        branches: [ master ]
        paths:
            - 'test/container/**'
            - '.github/workflows/container.yml'

    workflow_dispatch:
        inputs:
            container:
                type: choice
                description: 'distro'
                default: 'debian'
                options:
                    - "alpine"
                    - "debian"
                    - "gentoo"

permissions:
    packages: write
    contents: read

jobs:
    push_to_registry:
        name: container
        runs-on: ubuntu-latest
        concurrency:
            group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.config.dockerfile }}
            cancel-in-progress: true
        strategy:
            fail-fast: false
            matrix:
                config:
                    - { tag: 'alpine', dockerfile: 'Dockerfile-alpine' }
                    - { tag: 'debian', dockerfile: 'Dockerfile-debian }
                    - { tag: 'gentoo', dockerfile: 'Dockerfile-gentoo }
                    - { tag: 'arch', dockerfile: 'Dockerfile-arch }
                    - { tag: 'fedora', dockerfile: 'Dockerfile-fedora }
                    - { tag: 'opensuse', dockerfile: 'Dockerfile-opensuse }

        steps:
            -   name: Check out the repo
                uses: actions/checkout@v2
            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v1
            -   name: Login to GitHub Container Registry
                uses: docker/login-action@v2
                with:
                    registry: ghcr.io
                    username: ${{ github.repository_owner }}
                    password: ${{ secrets.GITHUB_TOKEN }}
            -   name: Set up env
                run: echo "repository_owner=${GITHUB_REPOSITORY_OWNER,,}" >>${GITHUB_ENV}
            -   name: Build and Push Container
                uses: docker/build-push-action@v3
                with:
                    file: test/container/${{ matrix.config.dockerfile }}
                    tags: ghcr.io/${{env.repository_owner}}/${{ matrix.config.tag }}
                    push: ${{ github.event_name == 'push' }}
