name: Container

on:
    workflow_dispatch:

permissions:
    packages: write
    contents: read

jobs:
    push_to_registry:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout
                uses: actions/checkout@v3
                with:
                  submodules: true

            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v2

            -   name: Login to GitHub Container Registry
                uses: docker/login-action@v2
                with:
                    registry: ghcr.io
                    username: ${{ github.repository_owner }}
                    password: ${{ secrets.GITHUB_TOKEN }}

            -   name: Set up env
                run: echo "repository_owner=${GITHUB_REPOSITORY_OWNER,,}" >>${GITHUB_ENV}

#            -   name: initramfs
#                uses: docker/build-push-action@v4
#                with:
#                    push: true
#                    file: container/Dockerfile-initramfs
#                    tags: ghcr.io/${{env.repository_owner}}/initramfs


#            -   name: kernel-tiny
#                uses: docker/build-push-action@v4
#                with:
#                    push: true
#                    file: container/Dockerfile-kernel-tiny
#                    tags: ghcr.io/${{env.repository_owner}}/kernel-tiny

            -   name: alpine
                uses: docker/build-push-action@v4
                with:
                    push: true
                    file: container/Dockerfile-Alpine
                    tags: ghcr.io/${{env.repository_owner}}/alpine-kernel-tiny
