name: Test
run-name: Test ${{ inputs.test }}

on:
    workflow_dispatch:
        inputs:
            test:
                description: 'Test to run'
                # TODO: fix test 16
                default: '03 10 11 14 98'
                required: true
            container:
                type: choice
                description: 'distro'
                default: 'alpine'
                options:
                    - "alpine"
                    - "debian"

jobs:
    test-release:
        runs-on: ubuntu-latest
        timeout-minutes: 45
        container:
            image: ghcr.io/${{github.repository_owner}}/${{inputs.container}}
            options: "--privileged -v /dev:/dev"
        steps:
            -   name: "Checkout Repository"
                uses: actions/checkout@v2
                with:
                    fetch-depth: 0

            -   name: "Get dracut tests"
                run: cd /usr/lib/dracut/test/ && cp -a TEST* Makefile run-qemu test-functions /__w/initramfs-modules/initramfs-modules/test/

            -   name: "Overlay dracut modules"
                run: cp -a /__w/initramfs-modules/initramfs-modules/modules.d/ /usr/lib/dracut/modules.d/

            -   name: "${{ inputs.container }} ${{ inputs.test }}"
                run: ./test/test.sh "TEST" "${{ inputs.test }}"
