name: Test
run-name: Test ${{ inputs.test }}

on:
    workflow_dispatch:
        inputs:
            test:
                description: 'Test to run'
                # TODO: fix test 16
                # passing on alpine default: '03 10 11 14 98'
                default: 70
                required: true
            container:
                type: choice
                description: distro
                default: debian
                options:
                    - alpine
                    - arch
                    - debian
                    - fedora
                    - gentoo
                    - opensuse

jobs:
    test-release:
        runs-on: ubuntu-latest
        timeout-minutes: 45
        container:
            image: ghcr.io/${{github.repository_owner}}/${{inputs.container}}
            options: "--privileged -v /dev:/dev"
        steps:
            -   name: "Checkout Repository"
                uses: actions/checkout@v2
                with:
                    fetch-depth: 0

            - name: Checkout tools repo
              uses: actions/checkout@v3
              with:
                repository: dracutdevs/dracut
                path: /dracut

            -   name: "Get dracut tests"
                run: find /__w/ && mkdir -p /usr/lib/dracut/test/ && cd /usr/lib/dracut/test/ && cp -a TEST* Makefile run-qemu test-functions /__w/initramfs-modules/initramfs-modules/test/ || true

            -   name: "Get dracut test modules"
                run: cp -av /usr/lib/dracut/modules.d/80test* /__w/initramfs-modules/initramfs-modules/modules.d/ || true

            -   name: "Overlay dracut modules"
                run: cp -av /__w/initramfs-modules/initramfs-modules/modules.d/* /usr/lib/dracut/modules.d/ && rm -rf /usr/lib/dracut/modules.d/*systemd*


            -   name: "Setup running tests"
                run: cp /usr/bin/dracut /usr/lib/dracut/dracut.sh

            -   name: "${{ inputs.container }} ${{ inputs.test }}"
                run: ./test/test.sh "TEST" "${{ inputs.test }}"
