name: Test

on:
    workflow_dispatch:
        inputs:
            test:
                description: 'Test to run'
                default: '80'
                required: true
            container:
                type: choice
                description: 'distro'
                default: 'alpine'
                options:
                    - "alpine"

jobs:
    test:
        runs-on: ubuntu-latest
        timeout-minutes: 45
        container:
            image: ghcr.io/${{ github.repository_owner }}/${{ inputs.container }}
            options: "--privileged -v /dev:/dev"
        steps:
            -   name: "Checkout Repository"
                uses: actions/checkout@v2
                with:
                    fetch-depth: 0

            -   name: "Overlay system dracut modules"
                run: rsync -av /__w/initramfs-modules/initramfs-modules/modules.d/ /usr/lib/dracut/modules.d/

            -   name: "Upstream tests"
                run: git clone https://github.com/dracutdevs/dracut.git && rsync -av dracut/test/TEST* /__w/initramfs-modules/initramfs-modules/test/ && rm -rf /__w/initramfs-modules/initramfs-modules/test/*SYSTEMD*

            -   name: "${{ inputs.container }} TEST-${{ inputs.test }}"
                run: ./test/test.sh "TEST-${{ inputs.test }}" ${{ inputs.test }}
