name: Test
run-name: Test ${{ inputs.test }}

on:
    workflow_dispatch:
        inputs:
            test:
                description: "Array of tests to run, such as [11,12]"
                default: "['00','01','03',10,11,12,13,14,15,16,17,98,30,35,40,20,50]"
                required: true
            container:
                type: choice
                description: distro
                default: debian
                options:
                    - debian
                    - gentoo
env:
    DEBUGFAIL: "${{ secrets.ACTIONS_STEP_DEBUG && 'rd.debug' }}"

jobs:
    test:
        runs-on: ubuntu-latest
        timeout-minutes: 30
        strategy:
            matrix:
                test: ${{ fromJSON(inputs.test) }}
            fail-fast: false
        container:
            image: ghcr.io/${{github.repository_owner}}/${{inputs.container}}
            options: "--privileged -v /dev:/dev"
        steps:
            -   name: "Checkout Repository"
                uses: actions/checkout@v3

            -   name: Checkout tools repo
                uses: actions/checkout@v3
                with:
                  repository: dracutdevs/dracut
                  path: dracut

            -   name: "Get dracut test cases"
                run: cp -an /__w/initramfs-modules/initramfs-modules/dracut/test/* /__w/initramfs-modules/initramfs-modules/test/ && rm -rf /__w/initramfs-modules/initramfs-modules/test/TEST*SYSTEMD

            -   name: "Install dracut test modules"
                run: cp -an /__w/initramfs-modules/initramfs-modules/dracut/modules.d/80test* /usr/lib/dracut/modules.d/

            -   name: "Install initramfs dracut modules"
                run: cp -an /__w/initramfs-modules/initramfs-modules/modules.d/* /usr/lib/dracut/modules.d/ && rm -rf /usr/lib/dracut/modules.d/*systemd*

            -   name: "Uninstall systemd dependent dracut modules"
                run: rm -rf /usr/lib/dracut/modules.d/*systemd*

            -   name: "Setup running tests"
                run: cp /usr/bin/dracut /usr/lib/dracut/dracut.sh

            -   name: "${{ inputs.container }} ${{ inputs.test }}"
                run: ./test/test.sh "TEST" "${{ matrix.test }}"
